spring.application.name=onlineshop

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}

spring.security.user.name=user
spring.security.user.password=user123

razorpay.api.key=rzp_test_TG4leoSLBTYTSM
razorpay.api.secretKey=ksx7AcnSoJ7OBcFWK0Bhvi6D